### ISSUE TITLE
Set up repository

### ISSUE THREAD

**Issue by ErikSRoth** [ThemeCore/themecore.org#1]
Initial setup of repository for ThemeCore .org website.
```[tasklist]
### Tasks
- [x] Add reademe file
- [x] add license file
- [x] add code of conduct file
- [x] add contriuting file
- [x] add main and child theme directories
- [x] add milestones
- [x] add label list
- [x] add gitkeep file
- [x] add gitignore file
```

**Comment by ErikSRoth** [comment]
Blank base files are added. All that is left to do is add the directory structure. 😎

**Comment by ErikSRoth** [comment]
Website theme folders add with a .gitkeep file so they can be pushed.
